# This is a basic workflow to help you get started with Actions

name: Build Packages with Unibuild

# Controls when the workflow will run
on:
  push:
    branches: [ unibuild ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/perfsonar/unibuild/alma8:latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: make
      
      # Upload RPMs as artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}-alma8
          path: unibuild-repo/
